name: Linux benchmark tests / LLVM 10.0

on:
  pull_request:
    branches: ['master']
  push:
    branches:
      - 'master'
      - '**test_bench**'

env:
  LLVM_VERSION: "10.0"
  LLVM_REPO: https://github.com/dbabokin/llvm-project
  LLVM_TAR: llvm-10.0.1-ubuntu16.04-Release+Asserts-x86.arm.wasm.tar.xz
  SDE_TAR_NAME: sde-external-8.56.0-2020-07-05-lin

jobs:
  linux-build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install bison flex libc6-dev-i386 g++-multilib lib32stdc++6 ncurses-dev
        wget $LLVM_REPO/releases/download/llvm-$LLVM_VERSION-ispc-dev/$LLVM_TAR
        tar xvf $LLVM_TAR 
        echo "::add-path::${GITHUB_WORKSPACE}/bin-$LLVM_VERSION/bin"

    - name: Check environment
      run: |
        ./check_env.py
        which -a clang
        cat /proc/cpuinfo

    - name: Build package
      run: |
        mkdir build && cd build
        cmake .. -DISPC_PREPARE_PACKAGE=ON -DISPC_INCLUDE_BENCHMARKS=ON
        make -j4 package

    - name: Sanity testing (make check-all, make test)
      run: |
        cd build
        bin/check_isa
        bin/ispc --support-matrix
        make check-all
        make ispc_benchmarks && make test

    - name: Upload package
      uses: actions/upload-artifact@v2
      with:
        name: ispc_llvm10_linux
        path: build/ispc-trunk-linux.tar.gz

  benchmarks:
    continue-on-error: true
    runs-on: [self-hosted, linux, bench]
    needs: linux-build
    steps:
    - name: Download package
      uses: actions/download-artifact@v2
      with:
        name: ispc_llvm10_linux
    - name: Install dependencies and unpack artifacts
      run: |
        tar xvf ispc-trunk-linux.tar.gz
        echo "::add-path::${GITHUB_WORKSPACE}/ispc-trunk-linux/bin"
        echo "::set-env name=LLVM_HOME::${GITHUB_WORKSPACE}"
        echo "::set-env name=ISPC_HOME::${GITHUB_WORKSPACE}"
    - name: Check environment
      run: cat /proc/cpuinfo
    - name: Tune system for benchmarking
      run: curl http://$StabilizerServer:7373/acquire
      if: always()
    - name: Running benchmarks
      run: |
        mkdir -p out
        export LD_LIBRARY_PATH=../lib
        for exec in $(find . -type f -perm -u+x); do $exec --benchmark_out=out/$(basename $exec).json $BENCH_SETTINGS ; done
      working-directory: ispc-trunk-linux/benchmarks/
      env:
        BENCH_SETTINGS: '--benchmark_repetitions=10'
    - name: Reset system performance
      run: curl http://$StabilizerServer:7373/release
      if: always()
    - name: Upload results
      uses: actions/upload-artifact@v2
      with:
        name: ispc_llvm10_linux_bench_results
        path: ispc-trunk-linux/benchmarks/out/*.json
    - name: Clean self-hosted runner
      run: rm -rf ${GITHUB_WORKSPACE:?}/* ${HOME:?}/* 
      if: always()
